### PR TITLE
API endpoint to delete audit log for a query

### PR DESCRIPTION
**Pull request by sunu**

### CODE REVIEW

**Comment by pudo** [comment]
Looks really good, but I'd add a single check in the blueprint function to see if `require(request.authz.logged_in)`) and test for that with a 403.

**Comment by pudo** [comment]
One more point that I realised just now: should we be using query arguments for the delete API? I feel like it's a little bit inconsistent with the API, which otherwise uses form/json data for POST data. Perhaps we could pull the text out of that instead of using the query URL param?

**Comment by davo11122** [comment]
@sunu Could you please provide a simple example of API request

**Comment by sunu** [comment]
@davo11122 to delete the search logs for the term "foo", the request will look something like
```
fetch("/api/2/querylog?query=foo", {
        method: "DELETE",
        headers: {...},
    }); 
```

**Pull request merged**
