### PR TITLE
#1796 Upgrade to Apple Silicon compatible node.js and bump node-sass too

### PR DESCRIPTION
**Pull request by Rosencrantz**
This contains changes from @pudo, but also an update to Node and node-sass. Node 16 introduces native support for Apple Silicon.

### CODE REVIEW

**Comment by pudo** [comment]
Very cool! I think it'd be good if @kjacks could give his thoughts on going to node16, and I guess we have to figure out how to do `arm64` builds of the ingestors before we can call this done.

**Comment by Rosencrantz** [comment]
Spoke with @kjacks yesterday, he's going to double check that there is nothing devastating in either the node or node-sass upgrades. But, right now, it looks good to merge.

**Comment by kjacks** [comment]
@Rosencrantz @pudo - Both the node-16 and node-sass updates seem all good to go for me. :) 
I played around with a workaround yesterday to try to get us onto dart-sass instead of node-sass bc it's deprecated, but it does seem like we're going to have to wait for the blueprint folks to: [catch up](https://github.com/palantir/blueprint/issues/4032) - which mayyybe might happen in blueprint v4.

For the bump to node-sass v.6.00, I re-ran the ui-prod build that was failing and it passed both locally and remotely, so I'm actually not sure why it failed the first time. From the release notes it seems like the changes are mostly related to tracking node versions anyways

**Comment by pudo** [comment]
Ok thanks for verifying this all, @kjacks! Let's take this into develop and see how it goes!

**Pull request merged**
