### PR TITLE
#572 Make Xref more specific - UI

### PR DESCRIPTION
**Pull request by felixebert**
screen shot 2018-12-17 at 08 21 58
screen shot 2018-12-17 at 08 22 14
screen shot 2018-12-17 at 08 22 25
screen shot 2018-12-17 at 08 23 06

### CODE REVIEW

**Comment by pudo** [comment]
Wow, that looks freaking awesome. Love the UX (perhaps the "Revise" button needs a different title, but I don't know what....).

**Comment by felixebert** [comment]
Thank you! How about "Review selected"? Idea is that you can review all your selected collections independent of the current filter settings and remove some before you submit the form

**Comment by davo11122** [comment]
Hey @felixebert, this is amazing! Agree "Revise" button could be more explaining! "Review selected" makes more sense, but I think about having a second(parallel) list of selected items below the main list. Any thoughts?

**Comment by pudo** [comment]
Thanks again for this amazing feature addition!

**Pull request merged**
