### PR TITLE
Till/docs

### LINKED ISSUE #2320: Incroporate Aleph documentation into Aleph
alephdata/docs is the repository where we currently keep all of our documentation, including the changelog.md that we use for the changes that occur within Aleph. This is confusing and for external teams running their own aleph instances there is no way for them to easily see changes between releases outside of checking the git log or having a seperate repo containing our documentation.

We should look at what is required to bring Alephs documentation into the product. The current documentation is here: https://github.com/alephdata/docs

### PR DESCRIPTION
**Pull request by tillprochaska**
**To do before merging:**

- [x] Change deploy condition to deploy on push to `main` only.
- [x] Change branch in `src/options.json` to `main`.
- [x] Set up CNAME for docs.aleph.occrp.org

**To do after merging:**
- [ ] Remove branch `till/docs` from environment protection rule.
- [ ] Set up redirect for docs.alephdata.org to docs.aleph.occrp.org

Close #2320

### CODE REVIEW

**Comment by tillprochaska** [comment]
@Rosencrantz @stchris I’ve updated this PR and I think it should be ready to be merged as a drop-in replacement for the current GitBook docs. The current version is deployed to https://alephdata.github.io/aleph/ in case you want to take another look :)

As mentioned before, there are other ongoing projects to improve the structure and quality of the documentation. While this PR contains a few minor content edits (typos, heading levels, …), it’s mostly about replacing GitBook with a self-hosted documentation setup.

**Review by stchris — APPROVED** [review]
Super cool outcome. Thanks for all the hard and dedicated work on this, @tillprochaska ! 

If you don't mind, I will just approve based on the result and without looking at the actual code changes 😁

**Comment by tillprochaska** [comment]
Thanks @stchris!

> If you don't mind, I will just approve based on the result and without looking at the actual code changes 😁

That’s absolutely fine! Most of the code actually lives in [alephdata/astro-theme-docs](https://github.com/alephdata/astro-theme-docs), this PR should mostly contain the actual documentation contents.

**Comment by Rosencrantz** [comment]
@tillprochaska Looks good, and I am going to merge this. One thing that we should take a look at is the menu for the technical FAQ. In my opinion this is a little hard to read right now and we should see if there is anything we can do to improve it.

**Pull request merged**
