### PR TITLE
Command-line groups support

### PR DESCRIPTION
**Pull request by simonwoerpel**
As outlined in #1522 

this introduces cli commands for `cretegroup`, `useradd`, `userdel`

I couldn't find any tests for the manage module, so I assume these simple cli commands have no tests? :thinking: 

I am happy to write some, though ;)

### CODE REVIEW

**Comment by simonwoerpel** [comment]
Erf, sorry, wtf there are many more commits in here as supposed to be. Will clean up asap

**Comment by sunu** [comment]
Hi @simonwoerpel! This looks perfect. We definitely want some tests for the new functions in `logic/roles.py` and `model/role.py`. If  you add some tests for manage.py commands as well that would be even better. We can add tests for other existing cli commands based on your new tests 😄

**Review by Rosencrantz — COMMENTED** [review]
As @sunu mentioned, first, Thank you! This all looks good, but we'd want a few tests around the new functions.

**Comment by Rosencrantz** [comment]
Hey @simonwoerpel Hope you're doing good. Have you had an opportunity to review the pull request and look into adding some tests around the changes you've made?

**Comment by Rosencrantz** [comment]
@simonwoerpel Did you ever manage to create or push any tests for this?

**Comment by tillprochaska** [comment]
Closing this as #3127 is now merged :)

**Pull request closed without merging**
