### PR TITLE
Next Release

### PR DESCRIPTION
**Pull request by sunu**

### CODE REVIEW

**Review by Rosencrantz — APPROVED** [review]

**Comment by Rosencrantz** [comment]
@sunu Might be worth adding the updated FtM?

**Comment by sunu** [comment]
Yes, I was hoping we can add the work on configurable facets to this release too. WDYT?

**Comment by Rosencrantz** [comment]
I'm happy for my stuff to got out. I'd really like to see some feedback from our users. @kjacks Are you comfortable with this?

**Comment by kjacks** [comment]
Before merging the configurable search screen PR I think it would be good to have a bit of time to test that the merge of Steve's branch into the main feature branch is all working as planned. Otherwise this looks good to go!

**Comment by sunu** [comment]
@kjacks I can deploy it to staging if you like and then we can click around a bit

**Comment by kjacks** [comment]
@sunu Sounds good!

**Pull request merged**
