### PR TITLE
Handle long role names

### LINKED ISSUE #1853: Share box layout breaks for long usernames
Hi, when sharing an investigation with a user who uses a long email or username, the box looks weird.

image

### PR DESCRIPTION
**Pull request by kjacks**
Fixes #1853

### CODE REVIEW

**Review by Rosencrantz — APPROVED** [review]
Truncation could come back and bite us in the future, but I agree it's the right solution for now.

**Comment by kjacks** [comment]
@Rosencrantz how so?

**Comment by Rosencrantz** [comment]
> @Rosencrantz how so?

In my experience, especially when work with internationalised products there comes a point where truncating text becomes detrimental, either because it truncates too much, or truncates just enough to make the text confusing, non unique, or unitelligable.

**Comment by kjacks** [comment]
Got it - yes, totally. In this case it feels manageable because we're just truncating the user's own name, so hopefully it shouldn't mess them up too much

**Comment by Rosencrantz** [comment]
@kjacks Did you want to merge this?

**Comment by kjacks** [comment]
@Rosencrantz it's ready to go

**Pull request merged**
