### PR TITLE
WIP Document processing status reports

### PR DESCRIPTION
**Pull request by pudo**
Just making a PR to make this easier to track

### CODE REVIEW

**Comment by pudo** [comment]
Closing this because it's out of sync badly. Can we make a clean one so we can move this forward?

**Comment by simonwoerpel** [comment]
Yes, totally out of sync. I am currently working on this to make it clean based on current 3.8 – please don't delete this pr / branch yet as I use it for reference... :upside_down_face:

**Comment by pudo** [comment]
Cool! How about we do multiple rounds this time: the indexer, the API and the UI?

**Comment by simonwoerpel** [comment]
exactly this is what i am on, there will be 3 commits at the end with these 3 things :upside_down_face:

**Pull request closed without merging**
