### PR TITLE
Add renameuser CLI command

### PR DESCRIPTION
**Pull request by catileptic**
Usage: 

`aleph renameuser user@example.com Bob`

To rename the default `Aleph` user, the command is:

`aleph renameuser default CorpName`

### CODE REVIEW

**Review by Rosencrantz — COMMENTED** [review]
Just a general thought, but what happens if a user tries to rename themselves to a name that is already in use in the system?

**Comment by Rosencrantz** [comment]
> 

Yeah, ignore me. This comment was not thought through, I can see that what I am thinking about is email.

**Comment by catileptic** [comment]
The name is only a label. The email is the unique identifier. So, duplicate names are fine.

**Review by Rosencrantz — COMMENTED** [review]
Looks good. No comments.

**Pull request merged**
